package com.meiya.time_task.moduls;

public class TimeTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_task.id
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_task.crom
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    private String crom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_task.id
     *
     * @return the value of time_task.id
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_task.id
     *
     * @param id the value for time_task.id
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_task.crom
     *
     * @return the value of time_task.crom
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    public String getCrom() {
        return crom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_task.crom
     *
     * @param crom the value for time_task.crom
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    public void setCrom(String crom) {
        this.crom = crom == null ? null : crom.trim();
    }
}