package com.meiya.time_task.mapper;

import com.meiya.time_task.moduls.TimeTask;
import org.springframework.stereotype.Repository;

@Repository
public interface TimeTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    int insert(TimeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    int insertSelective(TimeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    TimeTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    int updateByPrimaryKeySelective(TimeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbg.generated Tue Feb 25 11:40:57 CST 2020
     */
    int updateByPrimaryKey(TimeTask record);
}