package com.meiya.authorization.mapper;

import com.meiya.authorization.entity.AuthorizationInfo;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 *  Mapper 接口
 * </p>
 *
 * @author jobob
 * @since 2020-06-30
 */
public interface AuthorizationInfoMapper extends BaseMapper<AuthorizationInfo> {

    Integer insertAuthorizationInfo(AuthorizationInfo authorizationInfo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization_info
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization_info
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int insertSelective(AuthorizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization_info
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    AuthorizationInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization_info
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int updateByPrimaryKeySelective(AuthorizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization_info
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int updateByPrimaryKey(AuthorizationInfo record);
}
