package com.meiya.authorization.mapper;

import com.meiya.authorization.entity.Authorizer;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 *  Mapper 接口
 * </p>
 *
 * @author jobob
 * @since 2020-06-30
 */
public interface AuthorizerMapper extends BaseMapper<Authorizer> {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int insertSelective(Authorizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    Authorizer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int updateByPrimaryKeySelective(Authorizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer
     *
     * @mbg.generated Thu Jul 02 11:56:07 CST 2020
     */
    int updateByPrimaryKey(Authorizer record);

    int insertAuthorizer(Authorizer authorizer);

    Authorizer selectAuthorizerByNameAndIdCard(Authorizer authorizer);
}
